DELETE http://localhost:3001/api/blogs/624ef7f6af8382d3aa7766ac
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkRhdmUiLCJpZCI6IjYyNGQ2NmVhZGM4YjU5NTIxNzhmNjU0MyIsImlhdCI6MTY0OTM0Mzk3NiwiZXhwIjoxNjQ5MzQ3NTc2fQ.m5Gckg4BWRaqZ0zATU5pVpB6wgDpc9Kx1kabzFEHf6o