name: Deploy

on:
  push:
    branches: [main]
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "puhelinluettelobackendjm"
          heroku_email: "jannemieskolainen@gmail.com"
          appdir: "osa3"
          procfile: "web: npm start"
          healthcheck: "https://puhelinluettelobackendjm.herokuapp.com/health"
          checkstring: "ok"
          rollbackonhealthcheckfailed: true